config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'exchanges#new'

  get 'get_quotes', to: 'currency_quotes#get_quote'

  resources :currency_quotes
  resources :exchanges
end

app/models/application_record.rb
# Application record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency_quote.rb
# CurrencyQuote record
class CurrencyQuote < ApplicationRecord
  def self.search_existing(base, target, date)
    CurrencyQuote.find_by(base: base,
                          target: target,
                          date: date)
  end
end

app/models/exchange.rb
# Exchange record
class Exchange < ApplicationRecord
  validates :base, :target, presence: true
  validates :amount, numericality: { only_float: true, greater_than: 0 }
  validates :weeks, inclusion: { in: 1..250 },
                    numericality: { greater_than: 0, less_than: 26 }
end

app/models/user.rb
# User record
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# Application controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/currency_quotes_controller.rb
# Currency Quotes controller
class CurrencyQuotesController < ApplicationController
end

app/controllers/exchanges_controller.rb
# Exchanges controller
class ExchangesController < ApplicationController
  include ExchangesHelper
  before_action :authenticate_user!

  def index
    @exchanges = Exchange.where(user_id: current_user.id)

    render :index
  end

  def new
    @exchange = Exchange.new
  end

  def create
    @exchange = Exchange.new(exchange_params)
    @exchange.user_id = current_user.id

    if @exchange.save
      flash[:notice] = 'Currency exchange was successfully created'
      redirect_to exchange_path(@exchange)
    else
      render :new
    end
  end

  def edit
    @exchange = Exchange.find(params[:id])
  end

  def update
    @exchange = Exchange.find(params[:id])
    if @exchange.update(exchange_params)
      redirect_to exchange_path(@exchange)
    else
      render :edit
    end
  end

  def show
    @exchange = Exchange.find(params[:id])

    @exchange_calculations = create_exchanges

    render :show
  end

  private def exchange_params
    params.require(:exchange).permit(:base, :target, :amount, :weeks)
  end

  def destroy
    @exchange = Exchange.find(params[:id])
    @exchange.destroy
    flash[:notice] = 'Currency exchange was successfully deleted!'

    redirect_to exchanges_path
  end
end

app/helpers/application_helper.rb
# Application helper
module ApplicationHelper
end

app/helpers/currency_quotes_helper.rb
# CurrencyQuotes helper
module CurrencyQuotesHelper
end

app/helpers/exchanges_helper.rb
# Exchanges helper
module ExchangesHelper
  API_URL = 'http://api.fixer.io/'.freeze

  def create_exchanges
    exchange = {}
    beginning_of_week = Date.today.beginning_of_week
    forecast_week = Date.today.beginning_of_week

    @exchange.weeks.times do |week|
      @currency_quote = CurrencyQuote.search_existing(@exchange.base,
                                                      @exchange.target,
                                                      beginning_of_week)

      request_quote(beginning_of_week) unless @currency_quote

      exchange[week] = { year: forecast_week.year,
                         week: forecast_week.cweek,
                         base: @exchange.base,
                         target: @exchange.target,
                         rate: @currency_quote.rate.to_f,
                         amount: (@exchange.amount.to_f *
                                  @currency_quote.rate.to_f).round(2) }

      beginning_of_week -= 7
      forecast_week += 7
    end

    calculate_rate_average(exchange)
    calculate_profits(exchange)
    rank_by_profit(exchange)

    exchange
  end

  def request_quote(beginning_of_week)
    api_data = HTTParty.get week_query(beginning_of_week)
    @currency_quote = CurrencyQuote.new(base: @exchange.base,
                                        target: @exchange.target,
                                        date: beginning_of_week,
                                        rate: api_data['rates'][@exchange.target])
    @currency_quote.save
  end

  def week_query(date)
    API_URL + date.to_s + '?' + { base: @exchange.base,
                                  symbols: @exchange.target }.to_query
  end

  def calculate_rate_average(exchange_data)
    all_rates = []
    exchange_data.each_value do |exchange|
      all_rates << exchange[:rate]
    end

    avg_rate = all_rates.inject { |sum, el| sum + el }.to_f / all_rates.size

    @exchange.avg_rate = avg_rate
  end

  def calculate_profits(exchange_data)
    exchange_data.each_value do |exchange|
      exchange[:profit] = (@exchange.amount.to_f * exchange[:rate].to_f -
          @exchange.amount.to_f * @exchange.avg_rate.to_f).round(2)
    end
  end

  def rank_by_profit(exchange_data)
    sorted_weeks = exchange_data.sort_by { |_k, v| v[:profit] }.reverse

    top_ranks = [3, sorted_weeks.count].min
    top_ranks.times do |rank|
      exchange_data[sorted_weeks[rank][0]][:rank] = rank + 1
    end
  end
end

app/views/exchanges/_form.html.erb
<%= render 'messages' %>

<%= form_for @exchange do |f| %>

    <div class="form-group row">
      <%= f.label :base, 'Base currency', class: 'col-sm-2 ml-auto col-form-label' %>
      <div class="col-sm-5 mr-auto">
        <%= f.select :base, options_for_select([['AUD', 'AUD'], ['BGN', 'BGN'], ['BRL', 'BRL'],
                                                ['CAD', 'CAD'], ['CHF', 'CHF'], ['CNY', 'CNY'],
                                                ['CZK', 'CZK'], ['DKK', 'DKK'], ['EUR', 'EUR'],
                                                ['GBP', 'GBP'], ['HKD', 'HKD'], ['HRK', 'HRK'],
                                                ['HUF', 'HUF'], ['IDR', 'IDR'], ['ILS', 'ILS'],
                                                ['INR', 'INR'], ['USD', 'USD']], @exchange.base), {}, {class: 'form-control'} %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :target, 'Target currency', class: 'col-sm-2 ml-auto col-form-label' %>
      <div class="col-sm-5 mr-auto">
        <%= f.select :target, options_for_select([['AUD', 'AUD'], ['BGN', 'BGN'], ['BRL', 'BRL'],
                                                  ['CAD', 'CAD'], ['CHF', 'CHF'], ['CNY', 'CNY'],
                                                  ['CZK', 'CZK'], ['DKK', 'DKK'], ['EUR', 'EUR'],
                                                  ['GBP', 'GBP'], ['HKD', 'HKD'], ['HRK', 'HRK'],
                                                  ['HUF', 'HUF'], ['IDR', 'IDR'], ['ILS', 'ILS'],
                                                  ['INR', 'INR'], ['USD', 'USD']], @exchange.target), {}, {class: 'form-control'} %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :amount, 'Amount', class: 'col-sm-2 ml-auto col-form-label' %>
      <div class="col-sm-5 mr-auto">
        <%= f.text_field :amount, class: 'form-control', :value => (number_with_precision(f.object.amount, :precision => 2) || 0) %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :weeks, 'Max. waiting time', class: 'col-sm-2 ml-auto col-form-label' %>
      <div class="col-sm-5 mr-auto">
        <%= f.number_field :weeks, class: 'form-control' %>
      </div>
    </div>

    <%= f.submit 'Calculate', class: 'btn btn-primary' %>

<% end %>

app/views/exchanges/_messages.html.erb
<% if @exchange.errors.any? %>
      <% @exchange.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger" role="alert">
          <%= content_tag :div, msg %>
        </div>
      <% end %>
<% end %>

app/views/exchanges/edit.html.erb
<div class="container">

  <h1>Edit currency exchange</h1>

  <%= render 'form' %>

</div>

app/views/exchanges/index.html.erb
<div class="container">

    <div class="tab-pane fade show active" id="nav-table" role="tabpanel" aria-labelledby="nav-table-tab">

      <table class="table">
        <thead>
        <tr>
          <th>Base</th>
          <th>Target</th>
          <th>Amount (converted)</th>
          <th>Weeks</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <% @exchanges.each do |exchange| %>
            <tr>
              <th scope="row">
                <%= exchange[:base].to_s %>
              </th>
              <td>
                <%= exchange[:target].to_s %>
              </td>
              <td>
                <%= exchange[:amount].to_s %>
              </td>
              <td>
                <%= exchange[:weeks].to_s %>
              </td>
              <td>
                <%= link_to 'Show', exchange_path(exchange) %>
                <%= link_to 'Edit', edit_exchange_path(exchange) %>
                <%= link_to 'Delete', exchange_path(exchange), method: :delete, data:{confirm: 'Are you sure?'}  %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/exchanges/new.html.erb
<div class="container">

  <h1>Create new currency exchange</h1>

  <%= render 'form' %>

</div>

app/views/exchanges/show.html.erb
<div class="container">

  <h1>
    <span>Showing Exchange</span>
    <%= link_to '<button type="button" class="btn btn-primary">Edit</button>'.html_safe, edit_exchange_path %>
  </h1>

  <div class="row">

    <div class="col-sm-6">
      <div>
        <label>Base currency: </label>
        <span><%= @exchange.base %></span>
      </div>
      <div>
        <label>Target currency: </label>
        <span><%= @exchange.target %></span>
      </div>
    </div>

    <div class="col-sm-6">
      <div>
        <label>Amount: </label>
        <span><%= @exchange.amount %></span>
      </div>
      <div>
        <label>Weeks: </label>
        <span><%= @exchange.weeks %></span>
      </div>
      <div>
        <label>Average rate: </label>
        <span><%= @exchange.avg_rate %></span>
      </div>
    </div>

  </div>




  <nav class="nav nav-tabs" id="exchangesTab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-table" role="tab" aria-controls="nav-home" aria-expanded="true">Table</a>
    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-graph" role="tab" aria-controls="nav-profile">Graph</a>
  </nav>

  <div class="tab-content" id="nav-tabContent">

    <div class="tab-pane fade show active" id="nav-table" role="tabpanel" aria-labelledby="nav-table-tab">

      <table class="table">
        <thead>
        <tr>
          <th>Year and week</th>
          <th>Exchange rate</th>
          <th>Amount (converted)</th>
          <th>Profit/Loss</th>
          <th>Rank</th>
        </tr>
        </thead>
        <tbody>
        <% @exchange_calculations.each_value do |exchange| %>
            <tr>
              <th scope="row">
                <%= exchange[:year].to_s %>: week <%= exchange[:week].to_s %>
              </th>
              <td>
                <%= exchange[:rate].to_s %>
              </td>
              <td>
                <%= exchange[:amount].to_s %> <%= @exchange.target %>
              </td>
              <td>
                <%= exchange[:profit].to_s %>
              </td>
              <td>
                <%= exchange[:rank].to_s %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="tab-pane fade" id="nav-graph" role="tabpanel" aria-labelledby="nav-graph-tab">
      <%= line_chart @exchange_calculations.each_value.pluck(:week, :profit), xtitle: 'week', ytitle: 'profit' %>
    </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => 'flash_#{name}' %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'ExChange', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="<%= 'nav-item active' if current_page?(new_exchange_path) %>">
        <%= link_to 'New', new_exchange_path, class: 'nav-link' %>
      </li>
      <li class="<%= 'nav-item active' if current_page?(exchanges_path) %>">
        <%= link_to 'List', exchanges_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>

  <%= link_to '<button type="button" class="btn btn-secondary">Logout</button>'.html_safe, destroy_user_session_path, method: :delete %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrencyExchange</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">
      <%= render 'layouts/messages' %>
    </div>

    <%= yield %>
  </body>
</html>